
GET http://localhost:5000/hello

###

GET http://localhost:5000/tasks

###
POST http://localhost:5000/tasks
Content-Type: application/json

{
    "name": "Vacuum house",
    "description": "Vacuum house"
}

###

GET http://localhost:5000/tasks/d2c8e5c1-7088-42e3-96de-a5f3a214351f

###

PUT http://localhost:5000/tasks/d2c8e5c1-7088-42e3-96de-a5f3a214351f
Content-Type: application/json

{
    "name": "Go to bed",
    "description": "Go to sleep"
}

###

DELETE http://localhost:5000/tasks/3d3fe390-0898-46cb-acaa-435b26b80f99


###

POST http://localhost:5000/users/register
Content-Type: application/json

{
    "email": "foobar@foo.com",
    "password": "test123"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "foobar@foo.com",
    "password": "test123"
}

###

POST http://localhost:5000/users/logout
Content-Type: application/json

###

POST http://localhost:5000/users/token
Content-Type: application/json
