AWSTemplateFormatVersion: "2010-09-09"
Description: Template to provision RDS database for task list application

Parameters:
  AccessSecurityGroup:
    Description: EC2 security group ID to authorise access to
    Type: AWS::EC2::SecurityGroup::Id
    Default: 'sg-02530679bb4e876c6'
  RDSVpc:
    Description: VPC to deploy RDS database to
    Type: AWS::EC2::VPC::Id
    Default: 'vpc-0ae5d449b16ec87db'
  RDSSubnets:
    Description: List of subnets to deploy RDS database into
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-04aaad4e3da714ac3,subnet-02be23a47dbedf823,subnet-0ab3478221f1b9e90'
  RDSPassword:
    Description: SSM parameter name for RDS database master password
    Type: AWS::SSM::Parameter::Value<String>
    Default: RDSPassword
    
Resources:
  RDSDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VPCSecurityGroups:
      - Ref: RDSDatabaseSecurityGroup
      DBSubnetGroupName: !Ref RDSDatabaseSubnetGroup
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.medium
      Engine: MySQL
      EngineVersion: '5.7.31'
      MasterUsername: admin
      MasterUserPassword: !Ref RDSPassword
      Tags: 
      - Key: auto-delete
        Value: no

  RDSDatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds: !Ref RDSSubnets

  RDSDatabaseSecurityGroup:
    Type:  AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group to provide access to RDS database
      SecurityGroupIngress:
      - FromPort: 3306
        ToPort: 3306
        IpProtocol: 'tcp'
        SourceSecurityGroupId: !Ref AccessSecurityGroup
      VpcId: !Ref RDSVpc
