apiVersion: v1
kind: Namespace
metadata:
  name: task-list
  labels:
    elbv2.k8s.aws/pod-readiness-gate-inject: enabled

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: task-list-api-config
  namespace: task-list
data:
  NODE_ENV: ${NODE_ENV}
  PORT: "${PORT}"
  DB_NAME: ${DB_NAME}
  DB_HOST: ${DB_HOST}
  DB_PORT: "${DB_PORT}"

---

apiVersion: v1
kind: Secret
metadata:
  name: task-list-api-secrets
  namespace: task-list
type: Opaque
data:
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
  REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: ${APP_IAM_ROLE_ARN}
  name: task-list-api
  namespace: task-list

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-list-api
  namespace: task-list
  labels:
    app: task-list-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-list-api
  template:
    metadata:
      labels:
        app: task-list-api
    spec:
      containers:
      - name: task-list-api
        image: ${ECR_REPOSITORY_URI}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        envFrom:
        - configMapRef:
            name: task-list-api-config
            optional: false
        - secretRef:
            name: task-list-api-secrets
            optional: false
        ports:
        - containerPort: 3000
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 70"]
      terminationGracePeriodSeconds: 120
      serviceAccountName: task-list-api

---

apiVersion: v1
kind: Service
metadata:
  namespace: task-list
  name: task-list-api
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app: task-list-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: task-list
  name: task-list-api
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: '/api/v1/health'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/tags: auto-delete=no
    alb.ingress.kubernetes.io/group.name: task-list
spec:
  rules:
  - host: tasklist.kevinf.xyz
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: task-list-api
            port:
              number: 3000
